version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.9
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - ./volumes/kafka/data:/bitnami/kafka/data
      - ./volumes/kafka/config:/bitnami/kafka/config
    networks:
      - sbdemo

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "10092:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - sbdemo

  db:
    image: postgres
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - sbdemo

  basket-producer:
    build:
      context: ../services/basket-producer
      dockerfile: Dockerfile
    image: basket-producer:latest
    container_name: basket-producer
    environment:
      - SPRING_DATASOURCE_URL:=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_R2DBC_URL:=r2dbc:postgresql://db:5432/postgres
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sbdemo

volumes:
  kafka_data:
    driver: local

networks:
  sbdemo:
    driver: bridge
